import os
import subprocess
from datetime import datetime
import re
import sys

def get_git_changes():
    try:
        # Get changes in the last 24 hours
        cmd = ['git', 'log', '--since="24 hours ago"', '--name-status', '--pretty=format:%h - %s (%an)']
        result = subprocess.run(cmd, capture_output=True, text=True)
        return result.stdout.strip()
    except Exception as e:
        return f"Error retrieving git log: {e}"

def check_deprecated_files():
    """Scans for files that might need cleanup."""
    deprecated = []
    for root, dirs, files in os.walk("."):
        if "deprecated" in root or "node_modules" in root or ".git" in root:
            continue
        for file in files:
            if "v2" in file and "v2." not in file: # heuristics
                 deprecated.append(os.path.join(root, file))
            # Check content for "DEPRECATED" marker
            try:
                path = os.path.join(root, file)
                with open(path, 'r', errors='ignore') as f:
                    if "DEPRECATED" in f.read():
                         deprecated.append(path)
            except:
                pass
    return deprecated

def generate_report():
    today = datetime.now().strftime("%Y%m%d")
    filename = f"Progress/PROGRESS_REPORT_{today}.md"

    # 1. Get Changes
    changes = get_git_changes()
    if not changes:
        changes_section = "No new commits in the last 24 hours."
    else:
        changes_section = changes

    # 2. Automated Checks
    deprecated_files = check_deprecated_files()
    automated_notes = ""
    if deprecated_files:
        automated_notes += "- **Potential Cleanup Needed**: Found 'DEPRECATED' or legacy-named files:\n"
        for f in deprecated_files:
            automated_notes += f"  - `{f}`\n"
    else:
        automated_notes += "- **Cleanup**: No obvious deprecated files found.\n"

    # 3. Dynamic Content
    # In a real daily workflow, this might pull from a TODO list or previous report
    # For now, we use a placeholder that encourages the user (or agent) to fill it in.

    content = f"""# 進捗管理レポート ({datetime.now().strftime('%Y-%m-%d')})

## 1. プロジェクト概要
**プロジェクト名**: X-AUTO-POST-SYSTEM-otakuDJ
**Status**: Active Development
**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 2. デイリーコードレビュー (Daily Code Review)

### Recent Changes (Last 24h)
{changes_section}

### Automated Analysis
{automated_notes}

### Manual Review Notes
<!-- Add specific code review comments here -->
- [Pending Manual Review]

## 3. アクションプラン (Action Plan)

### Today's Tasks Completed
- [x] Generated Daily Report
<!-- Add completed tasks -->

### Next Steps
<!-- Add next steps -->
1. Review automated analysis findings.
2. Continue development on...

---
*Report generated by Kotaro Progress Script*
"""

    os.makedirs("Progress", exist_ok=True)
    # Don't overwrite if exists, unless forced?
    # Actually, for this task, I want to update the script but NOT overwrite the good report I just made manually.
    # But for the sake of the "tool", I will write it if it doesn't exist.

    if os.path.exists(filename):
        print(f"Report {filename} already exists. Skipping overwrite.")
        print("To force overwrite, delete the file first.")
    else:
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Generated {filename}")

if __name__ == "__main__":
    generate_report()
